platform :ios, '10.0'

target 'Sample' do
  use_frameworks!

  pod 'SamplePod', :path => 'SamplePod'

end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
